# Generated by Django 4.2 on 2026-01-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Industry Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(max_length=500, verbose_name='Icon Path')),
                ('gradient', models.CharField(help_text='CSS gradient for card background', max_length=200, verbose_name='Gradient CSS')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('role', models.CharField(max_length=200, verbose_name='Role/Position')),
                ('service', models.CharField(max_length=200, verbose_name='Service Provided')),
                ('review_text', models.TextField(verbose_name='Review')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('color_start', models.CharField(default='#441AAD', help_text='Hex color code (e.g., #441AAD)', max_length=7, verbose_name='Gradient Start Color')),
                ('color_end', models.CharField(default='#2A0E6E', help_text='Hex color code (e.g., #2A0E6E)', max_length=7, verbose_name='Gradient End Color')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which approved reviews appear on the site', verbose_name='Display Order')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the review was approved/rejected', null=True, verbose_name='Reviewed At')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('pdf_file', models.FileField(help_text='Upload the PDF template', upload_to='templates/pdfs/', verbose_name='PDF File')),
                ('preview_image', models.ImageField(blank=True, help_text='Optional preview image for the template', null=True, upload_to='templates/previews/', verbose_name='Preview Image')),
                ('description', models.TextField(blank=True, help_text='Optional description of the template', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is visible on the site', verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.industry', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['industry', 'order', 'name'],
            },
        ),
    ]
