# Generated by Django 4.2.19 on 2026-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional company logo', null=True, upload_to='reviews/logos/', verbose_name='Company Logo'),
        ),
    ]
